[project]
name = "github-activity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.10.6",
    "requests>=2.32.3",
    "rich>=13.9.4",
]
